/**
 * Snippets API
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("EventsApi", () => {
  let instance: api.EventsApi
  beforeEach(function() {
    instance = new api.EventsApi(config)
  });

  test("eventsCreate", () => {
    const body: api.EventCreate = undefined
    return expect(instance.eventsCreate(body, {})).resolves.toBe(null)
  })
  test("eventsDelete", () => {
    const id: number = 56
    return expect(instance.eventsDelete(id, {})).resolves.toBe(null)
  })
  test("eventsFeatured", () => {
    return expect(instance.eventsFeatured({})).resolves.toBe(null)
  })
  test("eventsList", () => {
    return expect(instance.eventsList({})).resolves.toBe(null)
  })
  test("eventsPartialUpdate", () => {
    const body: api.Event = undefined
    const id: number = 56
    return expect(instance.eventsPartialUpdate(body, id, {})).resolves.toBe(null)
  })
  test("eventsRead", () => {
    const id: number = 56
    return expect(instance.eventsRead(id, {})).resolves.toBe(null)
  })
  test("eventsTicketsCreate", () => {
    const body: api.Ticket = undefined
    const event_id: string = "event_id_example"
    return expect(instance.eventsTicketsCreate(body, event_id, {})).resolves.toBe(null)
  })
  test("eventsTicketsDelete", () => {
    const event_id: string = "event_id_example"
    const id: string = "id_example"
    return expect(instance.eventsTicketsDelete(event_id, id, {})).resolves.toBe(null)
  })
  test("eventsTicketsList", () => {
    const event_id: string = "event_id_example"
    return expect(instance.eventsTicketsList(event_id, {})).resolves.toBe(null)
  })
  test("eventsTicketsPartialUpdate", () => {
    const body: api.Ticket = undefined
    const event_id: string = "event_id_example"
    const id: string = "id_example"
    return expect(instance.eventsTicketsPartialUpdate(body, event_id, id, {})).resolves.toBe(null)
  })
  test("eventsTicketsRead", () => {
    const event_id: string = "event_id_example"
    const id: string = "id_example"
    return expect(instance.eventsTicketsRead(event_id, id, {})).resolves.toBe(null)
  })
  test("eventsTicketsUpdate", () => {
    const body: api.Ticket = undefined
    const event_id: string = "event_id_example"
    const id: string = "id_example"
    return expect(instance.eventsTicketsUpdate(body, event_id, id, {})).resolves.toBe(null)
  })
  test("eventsUpdate", () => {
    const body: api.Event = undefined
    const id: number = 56
    return expect(instance.eventsUpdate(body, id, {})).resolves.toBe(null)
  })
})

describe("OrganizationApi", () => {
  let instance: api.OrganizationApi
  beforeEach(function() {
    instance = new api.OrganizationApi(config)
  });

  test("organizationCreate", () => {
    const body: api.OrganizationCreate = undefined
    return expect(instance.organizationCreate(body, {})).resolves.toBe(null)
  })
  test("organizationDelete", () => {
    return expect(instance.organizationDelete({})).resolves.toBe(null)
  })
  test("organizationList", () => {
    return expect(instance.organizationList({})).resolves.toBe(null)
  })
  test("organizationPartialUpdate", () => {
    const body: api.Organization = undefined
    return expect(instance.organizationPartialUpdate(body, {})).resolves.toBe(null)
  })
  test("organizationRead", () => {
    const org_id: string = "org_id_example"
    return expect(instance.organizationRead(org_id, {})).resolves.toBe(null)
  })
})

describe("UsersApi", () => {
  let instance: api.UsersApi
  beforeEach(function() {
    instance = new api.UsersApi(config)
  });

  test("usersAuthTokenCreate", () => {
    const body: api.TokenObtainPair = undefined
    return expect(instance.usersAuthTokenCreate(body, {})).resolves.toBe(null)
  })
  test("usersAuthTokenRefreshCreate", () => {
    const body: api.TokenRefresh = undefined
    return expect(instance.usersAuthTokenRefreshCreate(body, {})).resolves.toBe(null)
  })
  test("usersEmailVerifyRead", () => {
    const token: string = "token_example"
    return expect(instance.usersEmailVerifyRead(token, {})).resolves.toBe(null)
  })
  test("usersMeList", () => {
    return expect(instance.usersMeList({})).resolves.toBe(null)
  })
  test("usersPasswordResetCreate", () => {
    const body: api.PasswordReset = undefined
    return expect(instance.usersPasswordResetCreate(body, {})).resolves.toBe(null)
  })
  test("usersPasswordResetRequestCreate", () => {
    const body: api.PasswordResetRequest = undefined
    return expect(instance.usersPasswordResetRequestCreate(body, {})).resolves.toBe(null)
  })
  test("usersRegisterCreate", () => {
    const body: api.UserRegistration = undefined
    return expect(instance.usersRegisterCreate(body, {})).resolves.toBe(null)
  })
  test("usersTicketsList", () => {
    return expect(instance.usersTicketsList({})).resolves.toBe(null)
  })
})

